;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-backspace
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-colon
        c-electric-semi&comma
        delete-indentation
        kill-region
        org-self-insert-command
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        mark-sexp
        ))
