;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-mode
        autopair-backspace
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        delete-indentation
        kill-region
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-defun
        mark-sexp
        ))
